services:
  kosync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kosync
    ports:
      - 8081:8081
    volumes:
      - ./data:/app/data
    environment:
      - RECEIVE_RANDOM_DEVICE_ID=False
      - OPEN_REGISTRATIONS=True
    restart: unless-stopped
