version: '3'
services:
  kosync:
    image: kosync:latest
    container_name: kosync
    ports:
      - 8081:8081
    volumes:
      - ./data:/app/data
    environment:
      - RECEIVE_RANDOM_DEVICE_ID=False
    restart: unless-stopped
